export const PATHS = {
  about: '/nosotros',
  account: '/cuenta',
  banners: '/anuncios',
  blog: '/blog',
  blogArticlesAdmin: '/articulos-blog',
  blogDetail: (id: string) => `/blog/${id}`,
  checkout: '/finalizar-compra',
  contact: '/contacto',
  deals: '/ofertas',
  faq: '/preguntas-frecuentes',
  home: '/',
  login: '/iniciar-sesion',
  loginCode: '/iniciar-sesion/codigo',
  myOrders: '/mis-compras',
  orders: '/pedidos',
  paymentMethods: '/metodos-pago',
  products: '/productos',
  recoverPassword: '/recuperar-contrasena',
  register: '/registro',
  resetPassword: '/restablecer-contrasena',
  syncStatus: '/sincronizacion',
  terms: '/terminos',
  users: '/usuarios',
  verifyEmail: '/verificar-correo',
} as const;
